"use client";
import { useEffect, useRef } from 'react';
// import Image from 'next/image'; // Not using next/image for poster directly to simplify

interface VideoPlayerProps {
  src: string;
  poster?: string;
  posterAiHint?: string;
  className?: string;
  title?: string; // Optional title for the video section
}

export function VideoPlayer({ src, poster, posterAiHint, className, title }: VideoPlayerProps) {
  const videoRef = useRef<HTMLVideoElement>(null);

  return (
    <div className={`w-full ${className}`}>
      {title && <h2 className="text-3xl sm:text-4xl font-bold text-foreground text-center mb-8 md:mb-12">{title}</h2>}
      <div className="aspect-video overflow-hidden rounded-xl shadow-2xl"> {/* Added rounded-xl and more shadow */}
        <video
          ref={videoRef}
          src={src}
          poster={poster} // Use the direct poster URL
          className="w-full h-full object-cover"
          playsInline
          controls
          loop
          muted 
          // autoPlay // Consider UX for autoplay
          data-ai-hint={posterAiHint} // Hint for the poster if generated by AI
        >
          Your browser does not support the video tag.
        </video>
      </div>
    </div>
  );
}
